name: Image

on:
  push:
    branches:
      - master
      - ci-image

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v1
        with:
          go-version: '1.12.1'
      - uses: actions/checkout@master
        working-directory: /go/src/github.com/argoproj/argo-cd
      - uses: actions/cache@v1
        working-directory: /go/src/github.com/argoproj/argo-cd
        with:
          path: ./vendor
          key: ${{ runner.os }}-go-${{ hashFiles('**/Gopkg.lock') }}
          restore-keys: |
            ${{ runner.os }}-go-
      - run: curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
        working-directory: /go/src/github.com/argoproj/argo-cd
      - run: ls ./vendor/${{ hashFiles('**/Gopkg.lock') }} || dep ensure -v && touch ./vendor/${{ hashFiles('**/Gopkg.lock') }}
        working-directory: /go/src/github.com/argoproj/argo-cd
      - run: echo done
#      - run: docker login docker.pkg.github.com --username $USERNAME --password $PASSWORD
#        env:
#          USERNAME: ${{ secrets.USERNAME }}
#          PASSWORD: ${{ secrets.TOKEN }}
#      - run: make image DOCKER_PUSH=true IMAGE_NAMESPACE=docker.pkg.github.com/argoproj/argocd IMAGE_TAG=$(cat ./VERSION)-${GITHUB_SHA::8}
